// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6SG46171IP2tdYpczivPWroZLomUHfyE',
    appId: '1:431898400640:android:8b6193e533cba3c189d365',
    messagingSenderId: '431898400640',
    projectId: 'chatting-app-634b5',
    storageBucket: 'chatting-app-634b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAsGGoGHU208VRCnKP5vu0qmvy6JQHGCs',
    appId: '1:431898400640:ios:df9bbb070431747d89d365',
    messagingSenderId: '431898400640',
    projectId: 'chatting-app-634b5',
    storageBucket: 'chatting-app-634b5.appspot.com',
    androidClientId: '431898400640-p7rlqavhqqbroap4da87didpofecck03.apps.googleusercontent.com',
    iosClientId: '431898400640-jbgrpgm58ukig9rl3ulul21mqfkuj7n4.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
